name: Deploy Highline Himalayas

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build static website
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p "${{ secrets.PORT }}" "${{ secrets.HOST }}" >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh \
            -i ~/.ssh/id_ed25519 \
            -p "${{ secrets.PORT }}" \
            "${{ secrets.USERNAME }}@${{ secrets.HOST }}" \
            "echo 'SSH CONNECTION SUCCESSFUL'"

      - name: Deploy out folder
        run: |
          scp -r \
            -i ~/.ssh/id_ed25519 \
            -P "${{ secrets.PORT }}" \
            ./out/. \
            "${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/${{ secrets.USERNAME }}/public_html/"